# Generated by Django 2.2.6 on 2020-04-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testrun_back', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
