# Generated by Django 2.2.6 on 2020-04-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testrun_back', '0003_auto_20200417_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
